#ifndef MSCI_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED
#define MSCI_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED

using namespace std;

namespace scifir
{

}

#endif // MSCI_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED
