#ifndef SCIFIR_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED
#define SCIFIR_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED

using namespace std;

namespace scifir
{

}

#endif // SCIFIR_CHEMISTRY_BIOCHEMISTRY_LIPID_HPP_INCLUDED
